---
 - name: installing and launching filebeat
   hosts: webservers
   become: yes
   tasks:
   - name: download filebeat deb
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

   - name: install firebeat deb
     command: sudo dpkg -i filebeat-7.4.0-amd64.deb

   - name: drop in filebeat.yml
     copy:
       src: /etc/ansible/files/filebeat-config.yml
       dest: /etc/filebeat/filebeat.yml

   - name: enable and configure system module
     command: filebeat modules enable system

   - name: setup filebeat
     command: filebeat setup

   - name: start filebeat service
     command: sudo systemctl start filebeat

   - name: enable service firebeat on boot
     systemd:
       name: filebeat
       enabled: yes

# - name: installing and launching metricbeat
#   hosts: webservers
#   become: yes
#   tasks:
#   - name: down metricbeat deb
#     command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

#   - name: install metricbeat deb
#     command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

#   - name: drop in metricbeat.yml
#     copy:
#       src: /etc/metricbeat/metricbeat.yml
#       dest: /etc/metricbeat/metricbeat.yml

#   - name: enable and configure system module
#     command: metricbeat modules enable docker

#   - name: setup metricbeat
#     command: metricbeat setup

#   - name: start metricbeat service
#     command: metricbeat -e

#   - name: enable service metricbeat on boot
#     systemd:
#       name: metricbeat
#       enabled: yes